### ISSUE TITLE
figure not showing

### ISSUE THREAD

**Issue by pplenck** [centuri-engineering/closed_loop#1]
I am trying to run the second part of the code on my jupiter notebook and I don't see any figure 
unfortunately I do not see any figure popping up. Should I configure my jupyter to allow that?
someone suggested:
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager 
$ jupyter labextension install bqplot

**Comment by glyg** [comment]
ha yes the widgets are often causing problems initially
The commands above are for jupyterlab, you should not need it if you use jupyter notebook .. Sometimes one needs to restart the notebook server after installing the widgets. 
You don't see the figure, but you see the number input widget or nothing at all?

**Comment by glyg** [comment]
I updated the repo with an environement.yml file,
You can update with
```sh
git pull -f
```

And then create the env with
```sh
conda env create -f environment.yml
``` 
And then
```sh
conda activate closed_loop
```

Maybe it will help to install all at once

If this doesn't help, I'll pass by Monday

**Comment by pplenck** [comment]
I restarted and it works now.
I got  another issue, I'll post it, don't need to read them immediately.
it's a great training
